package ai.nextgenlabs.domain.enums;

public enum AuditAction {
    // Contact CRM
    CONTACT_CREATED,
    CONTACT_VIEWED,
    CONTACT_ASSIGNED,
    CONTACT_RESPONDED,
    CONTACT_STATUS_CHANGED,
    CONTACT_CLOSED,
    // Auth & security
    ADMIN_LOGIN_SUCCESS,
    ADMIN_LOGIN_FAILED,
    MFA_SUCCESS,
    MFA_FAILED,
    MFA_ENABLED,
    MFA_DISABLED,
    ACCOUNT_LOCKED,
    ACCOUNT_UNLOCKED,
    PASSWORD_RESET,
    PASSWORD_CHANGED,
    TOKEN_REFRESHED,
    TOKEN_REUSE_DETECTED,
    ADMIN_LOGOUT
}
